apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-controller
  labels:
    app: mcp-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcp-controller
  template:
    metadata:
      labels:
        app: mcp-controller
    spec:
      containers:
      - name: mcp-controller
        image: mcpcontroller:latest
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: tenant-id
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-controller
spec:
  selector:
    app: mcp-controller
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP