apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
type: Opaque
data:
  tenant-id: BASE64_ENCODED_TENANT_ID
  client-id: BASE64_ENCODED_CLIENT_ID
  client-secret: BASE64_ENCODED_CLIENT_SECRET
  openai-key: BASE64_ENCODED_OPENAI_KEY
  openai-endpoint: BASE64_ENCODED_OPENAI_ENDPOINT